/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.suanki.app

object App {
  val flightDf = FlightData.getData

  def main(args: Array[String]): Unit = {
    println("=" * 50)
    flightDf.show()
  }

  def greeting(): String = {

    "Pihu"
  }

}
