/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.suanki.app

object App {

  def main(args: Array[String]): Unit = {
    println("=" * 50)
  }

  def greeting(): String = {
    "Pihu"
  }

}
