/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.suanki.scala-spark-library-conventions")
    application
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass.set("com.suanki.app.App")
}